"""THE REAL WINDY CITY LEDGER — Streamlit Cloud entry point.

Deploy on Streamlit Community Cloud with this file as the "main file".
Everything it renders is read-only evidence from the committed SQLite ledger
(data/engine.db) and the static page (public/index.html) regenerated by the
GitHub Action in .github/workflows/civic-cycle.yml.
"""
from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st
import streamlit.components.v1 as components

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from engine import db  # noqa: E402

st.set_page_config(page_title="The Real Windy City Ledger",
                   page_icon="🌬", layout="wide")

if not (ROOT / "data" / "engine.db").exists():
    db.init_db()  # first boot on a fresh clone: empty-but-honest ledger

conn = db.connect()

tabs = st.tabs(["◈ The Ledger", "🚩 Alerts", "⚠️ Silent Edits",
                "🔎 Search", "✉️ Paperwork"])

with tabs[0]:
    page = ROOT / "public" / "index.html"
    if page.exists():
        components.html(page.read_text(), height=3400, scrolling=True)
    else:
        st.warning("public/index.html not built yet — the civic-cycle Action "
                   "creates it after the first crawl.")

with tabs[1]:
    st.subheader("Watchlist alerts — verbatim quotes, source links, fetch times")
    rows = conn.execute(
        "SELECT a.created_at, a.term, a.snippet, d.url, d.title FROM alerts a "
        "JOIN documents d ON d.id=a.document_id ORDER BY a.id DESC LIMIT 300"
    ).fetchall()
    for r in rows:
        with st.expander(f"{r['created_at']} · {r['term']} · {r['title']}"):
            st.markdown(f"> {r['snippet']}")
            st.markdown(f"[source record]({r['url']})")

with tabs[2]:
    st.subheader("Silent edits (SHA-256 drift on published pages)")
    rows = conn.execute(
        "SELECT v.captured_at, v.seq, v.change_summary, d.url, d.title "
        "FROM versions v JOIN documents d ON d.id=v.document_id "
        "WHERE v.seq>1 ORDER BY v.id DESC").fetchall()
    if rows:
        for r in rows:
            st.warning(f"**{r['title']}** — seq {r['seq']} · {r['captured_at']} · "
                       f"{r['change_summary']} · [source]({r['url']})")
    else:
        st.success("None yet. A quiet ledger is a true report.")

with tabs[3]:
    q = st.text_input("Search the ledger", "annexation")
    if q:
        hits = db.search(conn, q)
        st.caption(f"{len(hits)} document(s) match")
        for r in hits:
            st.markdown(f"**doc #{r['doc_id']}** · `{r['source']}` · {r['title']}")
            if r.get("snip"):
                st.markdown(f"> {r['snip']}")

with tabs[4]:
    st.info("Drafts are review-and-send. The machine does not mail letters; you sign, you send.")
    rows = conn.execute(
        "SELECT id, kind, subject, created_at, body FROM requests "
        "ORDER BY id DESC LIMIT 50").fetchall()
    for r in rows:
        with st.expander(f"#{r['id']} [{r['kind']}] {r['subject']} · {r['created_at']}"):
            st.markdown(r["body"])

st.caption("Engine v0.1 · public documents only · robots.txt honored · "
           "no affiliation with any individual, candidate, or committee")
