"""Module 5 (action drafts): Wyoming Public Records Act requests + public
comments. Output is a DRAFT. A human reviews, signs, and sends (LEGAL.md §4).
Statute cited is Wyoming's — Wyo. Stat. §§ 16-4-201 through 16-4-205 — because
FOIA only covers federal agencies.
"""
from __future__ import annotations

from . import db

PRA_BODY = """\
{requester_name}
{requester_contact}

{date}

Records Custodian
{custodian_office}
{custodian_address}

**PUBLIC RECORDS REQUEST under the Wyoming Public Records Act,
Wyo. Stat. §§ 16-4-201 through 16-4-205**

Dear Records Custodian:

Pursuant to the Wyoming Public Records Act, I request access to and copies of
the following public records:

  RECORDS SOUGHT:
  {records_description}

  DATE RANGE: {date_range}

To narrow the request: I prefer records in electronic format (email or
download). If any records are withheld, please identify each withheld document
and cite the specific statutory exemption authorizing the withholding, as the
Act requires denials to be grounded in its provisions.

If you estimate fees for this request will exceed {fee_limit}, please provide a
written cost estimate before proceeding so I can narrow or confirm the request.

I understand you will acknowledge receipt and produce the records within a
reasonable time consistent with Wyo. Stat. § 16-4-202. Please contact me with
any questions that would help you locate these records.

Thank you for your assistance.

Sincerely,

{requester_name}
{drafted_note}
"""

COMMENT_BODY = """\
PUBLIC COMMENT — DR AFT FOR REVIEW BEFORE SUBMISSION

To: {body_name}
Re: {agenda_item}
Meeting date: {meeting_date}

Members of {body_name}:

My name is {requester_name}, and I am a resident of {ward_or_area}.

1) POSITION: {position}

2) FACTS ON THE RECORD (each must carry a citation — verify before sending):
{fact_bullets}

3) SPECIFIC REQUEST: {ask}

Please include this comment in the public record for {agenda_item}.

Respectfully,
{requester_name}
{requester_contact}
"""


def generate_pra(conn, records_description: str, date_range: str,
                 custodian_office: str = "City Clerk's Office, City of Cheyenne",
                 custodian_address: str = "2101 O'Neil Ave., Cheyenne, WY 82001",
                 requester_name: str = "[YOUR NAME]",
                 requester_contact: str = "[YOUR ADDRESS / EMAIL / PHONE]",
                 fee_limit: str = "$25") -> str:
    body = PRA_BODY.format(
        requester_name=requester_name,
        requester_contact=requester_contact,
        date=db.utcnow()[:10],
        custodian_office=custodian_office,
        custodian_address=custodian_address,
        records_description=records_description,
        date_range=date_range,
        fee_limit=fee_limit,
        drafted_note="_[Draft generated by Civic Transparency Engine {ts} — "
                     "review and send manually; not legal advice.]_".format(
                         ts=db.utcnow()),
    )
    rid = db.save_request(conn, "prA".lower(), records_description[:80], body)
    return body


def generate_public_comment(conn, body_name: str, agenda_item: str,
                            meeting_date: str, position: str, ask: str,
                            fact_bullets: str,
                            ward_or_area: str = "Cheyenne",
                            requester_name: str = "[YOUR NAME]",
                            requester_contact: str = "[YOUR CONTACT]") -> str:
    body = COMMENT_BODY.format(
        body_name=body_name, agenda_item=agenda_item, meeting_date=meeting_date,
        requester_name=requester_name, ward_or_area=ward_or_area,
        position=position, fact_bullets=fact_bullets, ask=ask,
        requester_contact=requester_contact,
    )
    db.save_request(conn, "comment", f"{body_name} — {agenda_item}"[:80], body)
    return body
